# Keyboard Quantizer B(2) => KQB firmware build workflow for BLE Micro Pro
name: Build KQB Firmware

# Workflow trigger settings - manual execution only
on:
  # Manual execution trigger with parameters
  workflow_dispatch:
    inputs:
      keymap:
        description: 'Select keymap type'
        required: true
        default: 'default'
        type: choice
        options:
          - 'default'
          - 'naginata_v16'
          - 'no_msc'

jobs:
  build:
    # Run on Ubuntu latest
    runs-on: ubuntu-latest
    env:
      KEYMAP: ${{ github.event.inputs.keymap }}
    steps:
      # Checkout repository with submodules
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install QMK build dependencies including arm-none-eabi-gcc
      - name: Install QMK dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3-pip gcc-arm-none-eabi binutils-avr avr-libc
          python3 -m pip install qmk

      # Clone BLE Micro Pro QMK Firmware
      - name: Clone BLE Micro Pro QMK Firmware
        run: |
          git clone --recursive --depth 1 -b bmp-vial-1.3.5 https://github.com/sekigon-gonnoc/vial-qmk.git qmk_firmware_bmp_vial

      # Install QMK build tools
      - name: Install QMK build tools
        working-directory: qmk_firmware_bmp_vial
        run: |
          pip3 install -r requirements.txt
          ./util/qmk_install.sh

      # Prepare keymap files for kqb product
      - name: Prepare keymap files
        run: |
          cd qmk_firmware_bmp_vial
          
          # Create kqb directory
          mkdir -p keyboards/sekigon/keyboard_quantizer/kqb
          
          # Copy kqb files from workspace
          cp -r $GITHUB_WORKSPACE/kqb/* keyboards/sekigon/keyboard_quantizer/kqb/
          
      # Fix BMP platform path issue
      - name: Fix BMP platform path issue
        working-directory: qmk_firmware_bmp_vial
        run: |
          # Create symlink to fix path resolution issue for BMP platform
          # The BMP build system looks for files in protocol/bmp/ but they're in tmk_core/protocol/bmp/
          mkdir -p protocol
          ln -s ../tmk_core/protocol/bmp protocol/bmp

      # Build KQB firmware
      - name: Build KQB firmware
        working-directory: qmk_firmware_bmp_vial
        env:
          ARCH: ARM
        run: |
          make sekigon/keyboard_quantizer/kqb:${{ env.KEYMAP }}:uf2

      # Archive built firmware as artifact
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: keyboard-firmware-kqb-${{ env.KEYMAP }}
          path: qmk_firmware_bmp_vial/.build/sekigon_keyboard_quantizer_kqb_${{ env.KEYMAP }}.uf2
          if-no-files-found: error  # Error if files not found
          retention-days: 7
