# Keyboard Quantizer B(2) => KQB firmware build workflow for BLE Micro Pro
name: Build KQB Firmware

# Workflow trigger settings - manual execution only
on:
  # Manual execution trigger with parameters
  workflow_dispatch:
    inputs:
      keymap:
        description: 'Select keymap type'
        required: true
        default: 'default'
        type: choice
        options:
          - 'default'
          - 'naginata_v16'
          - 'no_msc'

jobs:
  build:
    # Run on Ubuntu latest
    runs-on: ubuntu-latest
    env:
      KEYMAP: ${{ github.event.inputs.keymap }}
    steps:
      # Checkout repository with submodules
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install QMK build dependencies including arm-none-eabi-gcc
      - name: Install QMK dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3-pip gcc-arm-none-eabi binutils-avr avr-libc
          sudo apt install -y build-essential gcc unzip wget zip gcc-avr binutils-avr avr-libc
          sudo apt install -y dfu-programmer dfu-util gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
          python3 -m pip install qmk

      # Clone BLE Micro Pro QMK Firmware
      - name: Clone BLE Micro Pro QMK Firmware
        run: |
          # Use the exact repository and branch as specified in requirements
          git clone --depth 1 -b dev/ble-micro-pro https://github.com/sekigon-gonnoc/vial-qmk.git qmk_firmware_bmp_vial
          cd qmk_firmware_bmp_vial
          # Try to get full history to ensure all files are available
          git fetch --unshallow || echo "Already unshallow or fetch failed"
          # Initialize and update all submodules with full depth
          git submodule update --init --recursive --depth 1
          git submodule foreach git fetch --unshallow || echo "Submodule unshallow failed"
          # Configure git user for tag creation
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          # Create a dummy tag to avoid git describe error
          git tag -a v0.0.1 -m "dummy tag for build"

      # Install QMK build tools
      - name: Install QMK build tools
        working-directory: qmk_firmware_bmp_vial
        run: |
          ./util/qmk_install.sh
          pip3 install -r requirements.txt
          # Setup QMK
          qmk setup -H $PWD -y
          # Verify BMP protocol files exist
          echo "Checking for BMP protocol files..."
          find . -name "bmp_settings.c" -type f || echo "bmp_settings.c not found"
          find . -name "bmp_settings.h" -type f || echo "bmp_settings.h not found"
          ls -la tmk_core/protocol/bmp/ || echo "BMP protocol directory not found"

      # Prepare keymap files for kqb product
      - name: Prepare keymap files
        run: |
          cd qmk_firmware_bmp_vial

          echo "Building for product: kqb, keymap: ${{ env.KEYMAP }}"

          # Check if keyboard_quantizer directory exists, if not create the full structure
          if [ ! -d "keyboards/sekigon/keyboard_quantizer/kqb" ]; then
            echo "Creating keyboard_quantizer/kqb directory structure"
            mkdir -p keyboards/sekigon/keyboard_quantizer/kqb
          fi

          # Create keymap directory if it doesn't exist
          mkdir -p keyboards/sekigon/keyboard_quantizer/kqb/keymaps/${{ env.KEYMAP }}

          # Copy all kqb files from workspace to ensure complete setup
          echo "Copying kqb files from workspace..."
          if [ -d "$GITHUB_WORKSPACE/kqb" ]; then
            # Copy all files except keymaps directory first
            find "$GITHUB_WORKSPACE/kqb" -maxdepth 1 -type f -exec cp {} keyboards/sekigon/keyboard_quantizer/kqb/ \;
            
            # Copy ld directory if it exists
            if [ -d "$GITHUB_WORKSPACE/kqb/ld" ]; then
              cp -r "$GITHUB_WORKSPACE/kqb/ld" keyboards/sekigon/keyboard_quantizer/kqb/
            fi
          fi

          # Copy keymap files from workspace if they exist
          if [ -d "$GITHUB_WORKSPACE/kqb/keymaps/${{ env.KEYMAP }}" ]; then
            cp -r "$GITHUB_WORKSPACE/kqb/keymaps/${{ env.KEYMAP }}/"* keyboards/sekigon/keyboard_quantizer/kqb/keymaps/${{ env.KEYMAP }}/
            echo "Copied custom keymap files for ${{ env.KEYMAP }}"
          else
            echo "Warning: Keymap ${{ env.KEYMAP }} not found in workspace, using default from repository"
          fi

          # List the contents to verify
          echo "Contents of keyboards/sekigon/keyboard_quantizer/kqb:"
          ls -la keyboards/sekigon/keyboard_quantizer/kqb/ || echo "Directory not found"
          echo "Contents of keymap directory:"
          ls -la keyboards/sekigon/keyboard_quantizer/kqb/keymaps/${{ env.KEYMAP }}/ || echo "Keymap directory not found"

          # Validate keymap exists
          if [ ! -f "keyboards/sekigon/keyboard_quantizer/kqb/keymaps/${{ env.KEYMAP }}/keymap.c" ]; then
            echo "Error: Invalid keymap: kqb/${{ env.KEYMAP }}"
            echo "Available keymaps:"
            ls -la keyboards/sekigon/keyboard_quantizer/kqb/keymaps/ || echo "Keymaps directory not found"
            exit 1
          fi

      # Build KQB firmware
      - name: Build KQB firmware
        working-directory: qmk_firmware_bmp_vial
        run: |
          # Build kqb firmware with specified keymap
          make sekigon/keyboard_quantizer/kqb:${{ env.KEYMAP }}:uf2
          ls -la .build/  # Show built files

      # Archive built firmware as artifact
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: keyboard-firmware-kqb-${{ env.KEYMAP }}
          path: qmk_firmware_bmp_vial/.build/sekigon_keyboard_quantizer_kqb_${{ env.KEYMAP }}.uf2
          if-no-files-found: error  # Error if files not found
          retention-days: 7
