# Keyboard Quantizer B(2) => KQB firmware build workflow for BLE Micro Pro
name: Build KQB Firmware

# Workflow trigger settings - manual execution only
on:
  # Manual execution trigger with parameters
  workflow_dispatch:
    inputs:
      keymap:
        description: 'Select keymap type'
        required: true
        default: 'default'
        type: choice
        options:
          - 'default'
          - 'naginata_v16'
          - 'no_msc'

jobs:
  build:
    # Run on Ubuntu latest
    runs-on: ubuntu-latest
    env:
      KEYMAP: ${{ github.event.inputs.keymap }}
    steps:
      # Checkout repository with submodules
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Install QMK dependencies including arm-none-eabi-gcc
      - name: Install QMK dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3-pip gcc-arm-none-eabi binutils-avr avr-libc
          sudo apt install -y build-essential gcc unzip wget zip gcc-avr binutils-avr avr-libc
          sudo apt install -y dfu-programmer dfu-util gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
          python3 -m pip install qmk

      # Clone BLE Micro Pro QMK Firmware
      - name: Clone BLE Micro Pro QMK Firmware
        run: |
          # Clone the main BMP QMK firmware repository directly to master branch
          git clone --recursive -b master https://github.com/sekigon-gonnoc/qmk_firmware.git qmk_firmware_bmp_vial
          cd qmk_firmware_bmp_vial
          # Ensure all submodules are updated
          git submodule update --init --recursive
          # Configure git user for tag creation
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          # Create a dummy tag to avoid git describe error
          git tag -a v0.0.1 -m "dummy tag for build"

      # Install QMK build tools
      - name: Install QMK build tools
        working-directory: qmk_firmware_bmp_vial
        run: |
          ./util/qmk_install.sh

      # Prepare keymap files for kqb product
      - name: Prepare keymap files
        run: |
          cd qmk_firmware_bmp_vial
          
          # Create kqb directory
          mkdir -p keyboards/sekigon/keyboard_quantizer/kqb
          
          # Copy kqb files from workspace
          cp -r $GITHUB_WORKSPACE/kqb/* keyboards/sekigon/keyboard_quantizer/kqb/

      # Build KQB firmware
      - name: Build KQB firmware
        working-directory: qmk_firmware_bmp_vial
        run: |
          make sekigon/keyboard_quantizer/kqb:${{ env.KEYMAP }}:uf2

      # Archive built firmware as artifact
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: keyboard-firmware-kqb-${{ env.KEYMAP }}
          path: qmk_firmware_bmp_vial/.build/sekigon_keyboard_quantizer_kqb_${{ env.KEYMAP }}.uf2
          if-no-files-found: error
          retention-days: 7
